version: "3.10"
services:
  worker:
    build: .
    environment:
      API_ID: $API_ID
      API_HASH: $API_HASH
      BOT_TOKEN: $BOT_TOKEN
      BOT_USERNAME: $BOT_USERNAME
      STRING_SESSION: $STRING_SESSION
      GROUP_SUPPORT: $GROUP_SUPPORT
      MONGODB_URL: $MONGODB_URL
      OWNER_ID: $OWNER_ID
      UPDATES_CHANNEL: $UPDATES_CHANNEL
